default: &default
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  db:  <%= ENV['REDIS_DB'] ||  0 %>

development:
  <<: *default
  db:  <%= ENV['REDIS_DB'] ||  1 %>
test:
  <<: *default
  db: <%= ENV['REDIS_DB'] ||  2 %>
integration:
  <<: *default
  db: <%= ENV['REDIS_DB'] ||  2 %>
staging:
  <<: *default
  db: <%= ENV['REDIS_DB'] ||  3 %>
production:
  <<: *default
  db: <%= ENV['REDIS_DB'] || 4 %>
