# This is the configuration used to check the rubocop source code.

require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/AccessorGrouping:
  Exclude:
    - lib/rubocop/formatter/base_formatter.rb
    - lib/rubocop/cop/offense.rb

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
    - spec/rubocop/cop/style/ip_addresses_spec.rb

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  AllowInHeredoc: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/InclusiveLanguage:
  FlaggedTerms:
    offence:
      Suggestions:
        - offense
  Exclude:
    - lib/rubocop/cop/naming/inclusive_language.rb

RSpec/FilePath:
  Exclude:
    - spec/rubocop/cop/internal_affairs/redundant_let_rubocop_config_new_spec.rb
    - spec/rubocop/formatter/junit_formatter_spec.rb

RSpec/PredicateMatcher:
  EnforcedStyle: explicit

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'

Performance/EndWith:
  SafeMultiline: false

Performance/StartWith:
  SafeMultiline: false

RSpec/StubbedMock:
  Enabled: false

InternalAffairs/ExampleDescription:
  Include:
    - 'spec/rubocop/cop/**/*.rb'

InternalAffairs/UndefinedConfig:
  Include:
    - 'lib/rubocop/cop/**/*.rb'
  Exclude:
    - 'lib/rubocop/cop/correctors/**/*.rb'
    - 'lib/rubocop/cop/mixin/**/*.rb'

InternalAffairs/StyleDetectedApiUse:
  Exclude:
    - 'lib/rubocop/cop/mixin/percent_array.rb'

Style/GuardClause:
  Enabled: false
